package:
  name: robotraconteur_companion_python
  version: 0.1.11

source:
  git_url: https://github.com/robotraconteur/robotraconteur_companion_python.git
  git_rev: v0.1.11

requirements:
  host:
    - python >=3.6
    - robotraconteur >=0.16
    - pyyaml
    - setuptools
    - importlib_resources
    - pip
    - general_robotics_toolbox >=0.7.1
  run:
    - python >=3.6
    - robotraconteur >=0.16
    - pyyaml
    - setuptools
    - importlib_resources
    - general_robotics_toolbox >=0.7.1

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

test:
  requires:
    - pytest
  source_files:
    - test/
  imports:
    - pytest
  commands:
    - pytest test/ --verbose --ignore test/test_urdf_loader.py

about:
  home: http://robotraconteur.com
  license: Apache-2.0
  summary: 'Companion library for the Robot Raconteur core library'

