package:
  name: robotraconteur_companion_python
  version: 0.1.9

source:
  git_url: https://github.com/robotraconteur/robotraconteur_companion_python.git
  git_depth: 10
  git_rev: v0.1.9

requirements:
  host:
    - python
    - robotraconteur
    - pyyaml
    - setuptools
    - importlib_resources
    - pip
  run:
    - python
    - robotraconteur
    - pyyaml
    - setuptools
    - importlib_resources

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: 'Companion library for the Robot Raconteur core library'

