{% set name = "robotraconteur_companion_python" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: 0.2.1

source:
  git_url: https://github.com/robotraconteur/robotraconteur_companion_python.git
  git_rev: v{{ version }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - robotraconteur >=0.16
    - pyyaml
    - setuptools
    - importlib_resources
    - pip
    - general_robotics_toolbox >=0.7.1
  run:
    - python >=3.6
    - robotraconteur >=0.16
    - pyyaml
    - setuptools
    - importlib_resources
    - general_robotics_toolbox >=0.7.1

test:
  requires:
    - pytest
  source_files:
    - test/
  imports:
    - pytest
  commands:
    - pytest test/ --verbose --ignore test/util/test_local_identifier_manager.py --ignore test/util/test_infofileloader.py

about:
  home: http://robotraconteur.com
  license: Apache-2.0
  summary: 'Companion library for the Robot Raconteur core library'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - johnwason
